---

- hosts: CAMPUS
  serial: 1

  vars_prompt:
   - name: output_file
     prompt: please enter output filename
     private: no
   - name: ansible_creds
     prompt: please enter ansible credentials
     private: yes


  tasks:
   - include: tasks/ospfneighbor.yml
   - include: tasks/vrfdetail.yml
   - include: tasks/iproutevrf-after.yml



   - name: create log file for all devices
     file: path=./reports/{{ output_file }}.all.txt state=touch

   - name: log to file for all devices
     lineinfile:
       insertafter: EOF
       path: ./reports/{{ output_file }}.all.txt
       line: '{{ item }}'
     with_items:
       - "#####{{inventory_hostname}}#####"
       - "{{ ospfneighbor }}"
       - "{{ vrfdetail }}"
       - "{{ iproutevrf_all }}"

   - name: create log file for individual device
     file: path=./reports/{{ output_file }}.{{inventory_hostname}}.txt state=touch

   - name: log to file for individual device
     lineinfile:
       insertafter: EOF
       path: ./reports/{{ output_file }}.{{inventory_hostname}}.txt
       line: '{{ item }}'
     with_items:
       - "#####{{inventory_hostname}}#####"
       - "{{ ospfneighbor }}"
       - "{{ vrfdetail }}"
       - "{{ iproutevrf_all }}"

