---

ntp_servers: 
  - 172.20.5.101
  
domain_name: iwan.lab

snmp_community:
  ro: LAB@APICEMro
  rw: LAB@APICEMrw

lan_key_chains: 
   - key_chain_name: LAN-KEY
     key_string: eigrp@LAN

eigrp_global:
  ent_eigrp:
    virtual_instances_name: ENTERPRISE-EIGRP
    ipv4_autonomous_system: 100
    af_interface_default:
      passive_interface: true