---
- hosts: dc

  tasks:
    - name: gather nxos facts
      nxos_facts:
        gather_subset: interfaces
        provider: "{{ nxoscli }}"
      register: results

    - name: view output
      debug:
        msg: "{{ results.ansible_facts.ansible_net_interfaces }}"

    - name: save output results
      template:
        src: "./templates/port-dest-status-report.j2"
        dest: './reports/devices/{{inventory_hostname}}-nxos-interface-report.csv'
        owner: ansible
        group: ansible_users
        mode: 0777

    - name: save output results
      assemble:
        src: ./reports/devices
        dest: './reports/nxos-interface-report.csv'
        owner: ansible
        group: ansible_users
        mode: 0777