---
- hosts: iwan

  tasks:
   
    - name: create wan documentation per device
      template:
        src: "./templates/reports/wan/iwan-documentation.j2"
        dest: './reports/wan/devices/{{inventory_hostname}}-intent.md'
        owner: ansible
        group: ansible_users
        mode: 0777

- hosts: localhost

  tasks:
  
    - name: create wan combinned documentation
      assemble:
        src: ./reports/wan/devices/
        dest: './reports/wan/README.md'
        owner: ansible
        group: ansible_users
        mode: 0777