---
- hosts: iwan

  tasks:
   
    - name: create documentation per device
      template:
        src: "./templates/reports/wan/iwan-documentation.j2"
        dest: './reports/wan/devices/{{inventory_hostname}}iwan-doc.md'
        owner: ansible
        group: ansible_users
        mode: 0777

#- hosts: localhost
#
#  tasks:
#  
#    - name: create combinned report
#      assemble:
#        src: ./reports/devices
#        dest: './reports/nxos-interface-report.csv'
#        owner: ansible
#        group: ansible_users
#        mode: 0777